### PR TITLE
Minor tweaks as I find them...

### PR DESCRIPTION
**Pull request by donalod**
Aside: I would also think about the rm -r in `rm_if_exists`, but that's only my paranoia as I know `mktemp` is using a path, but I like to cd to a well know directory path and then only rm -r the named remainder of a custom path. (Perhaps I would be worried someone would change the tmp path (i.e. tmpDir) and/or get it wrong and wipe out some parent structure, but I have not edited/suggested the fix in the script for that yet.

### CODE REVIEW

**Comment by BigMacAdmin** [comment]
Perhaps I'm showing my ignorance on this, but what is the purpose of including `#!/usr/bin/env bash` by default in this script?

In my estimation, it could only add potential issues if there are variable conflicts or something in the bash environment on the target device. I don't want to assume that some other admin hasn't added something that might much things up, but it's very possible I don't fully have my head around why folks would do this.

What is the use case for including environmental variables on something self contained like this?

**Comment by donalod** [comment]
Just a hangover for portability but I guess it could be a double edged sword depending on the user’s ENV. I can edit ✍️ and re-submit if you want… the hope would be that macOS never changes the bash path (even though it’s not the default any longer!).

**Review by BigMacAdmin — CHANGES_REQUESTED** [review]
Thanks for the improvements and the feedback!

Please remove the new "shebang" and leave at the existing `#!/bin/bash` 

Please iterate the script version to: 2.2.1

**Review by BigMacAdmin — APPROVED** [review]

**Comment by donalod** [comment]
I think that's done as per request. If I change my version further (and it's relevant to this generic one) I'll circle back with more suggestions for consideration ;)

**Pull request merged**
